host: localhost:8000/api
info:
  contact: {}
  description: Rating List Monitoring Platform API
  title: Rating List Monitoring Platform
  version: "1.0"
paths: {}
securityDefinitions:
  AccessTokenHeader:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
