server:
  port: "8001"
  max_header_bytes: 1048576
  read_timeout: 10
  write_timeout: 10

db:
  driver: "postgres"
  host: "rlmp-db"
  port: "5433"
  username: "ythosa"
  dbname: "rlmp"
  sslmode: "disable"
  migrations_path: "/usr/src/app/schema"

cache:
  address: "rlmp-cache:6379"
  password: ""
  db: 0

auth:
  access_token:
    ttl: 60
    signing_key: "81hJ!*@#Y&12yN#UI!Yjfklsjdf"
  refresh_token:
    ttl: 43200
    signing_key: "410fj12fjhsdfjksaj(UY^JIJ98adsuJIKDiHA&*"

parsing:
  rating_list_ttl: 120
  read_timeout: 10
  read_buffer_size: 6291456
  max_response_body_size: 16777216
  max_conns_per_host: 10
